# Generated by Django 4.0.3 on 2022-03-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_holidayinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikedislike',
            name='dislikes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postlikedislike',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
