version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r social_app/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 social_app/manage.py test

workflows:
  version: 2
  build-project:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - circleci