version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "social_app/requirements.txt" }}
      - run:
          name: Install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd social_app
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "social_app/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd social_app
            python3 manage.py test

workflows:
  version: 2
  build-project:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main